### ISSUE TITLE
"author" field does not get escaped

### ISSUE THREAD

**Issue by ryanakca** [pote/planet.rb#53]
The contents of the `author` field from planet.yml should get put between quotes when outputting the headers for the posts files. For example,

```
blogs:
  # Bare minimum to get it working
  - author: "Foo Bar: My Daily Frobnication"
    feed: "https://foo.bar/feed.xml"
    image: "https://foo.bar/myhead.jpg"
```

will lead to errors similar to the following when running `jekyll build`:

```
Error reading file /..../source/_posts/2015-10-12-runtime-tagging.markdown: (<unknown>): mapping values are not allowed in this context at line 5 column 22
```

This is because the header is:

```
---
title: "Runtime Tagging"
kind: article
created_at: 2015-10-12 00:00:00 UTC
author: Foo Bar: My Daily Frobnication
categories:
tags:
layout: post
---
```

instead of

```
---
title: "Runtime Tagging"
kind: article
created_at: 2015-10-12 00:00:00 UTC
author: "Foo Bar: My Daily Frobnication"
categories:
tags:
layout: post
---
```

I thought of patching as follows, but it doesn't seem to cause any change in the generated files.

```
diff --git a/bin/planet b/bin/planet
index 44e89e3..7bd6375 100755
--- a/bin/planet
+++ b/bin/planet
@@ -153,7 +153,7 @@ __END__
 title: "{{ post_title }}"
 kind: article
 created_at: {{ post_date }}
-author: {{ author }}
+author: "{{ author }}"
 categories: {{ blog_categories }}
 tags: {{ blog_tags }}
 layout: post
```
